baseURL = "/"
languageCode = "en"
title = "MYTechHubPro"
theme = "PaperMod"

[pagination]
  pagerSize = 10

defaultContentLanguage = "fa"
defaultContentLanguageInSubdir = true

[languages]

  [languages.fa]
    languageName = "ÙØ§Ø±Ø³ÛŒ ğŸ‡®ğŸ‡·"
    weight = 1
    contentDir = "content/fa"

  [languages.en]
    languageName = "English ğŸ‡¬ğŸ‡§"
    weight = 2
    contentDir = "content/en"

  [languages.de]
    languageName = "Deutsch ğŸ‡©ğŸ‡ª"
    weight = 3
    contentDir = "content/de"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "ğŸ  Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "â„¹ï¸ About"
    url = "/about/"
    weight = 2
