baseURL = "/"
languageCode = "fa"
title = "MYTechHubPro"
theme = "PaperMod"

# ØµÙØ­Ù‡â€ŒØ¨Ù†Ø¯ÛŒ
[pagination]
  pagerSize = 10

# Ø²Ø¨Ø§Ù† Ù¾ÛŒØ´â€ŒÙØ±Ø¶
defaultContentLanguage = "fa"
defaultContentLanguageInSubdir = true

# ØªÙ†Ø¸ÛŒÙ…Ø§Øª Ø²Ø¨Ø§Ù†â€ŒÙ‡Ø§
defaultContentLanguage = "fa"
defaultContentLanguageInSubdir = true

[languages]

  [languages.fa]
    languageName = "ÙØ§Ø±Ø³ÛŒ ğŸ‡®ğŸ‡·"
    weight = 1
    contentDir = "content/fa"

  [languages.en]
    languageName = "English ğŸ‡¬ğŸ‡§"
    weight = 2
    contentDir = "content/en"

  [languages.de]
    languageName = "Deutsch ğŸ‡©ğŸ‡ª"
    weight = 3
    contentDir = "content/de"


# Ù…Ù†ÙˆÙ‡Ø§
[menu]

  [[menu.main]]
    identifier = "home"
    name = "ğŸ  Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "â„¹ï¸ About"
    url = "/about/"
    weight = 2

